### ISSUE TITLE
How to use this crate?

### ISSUE THREAD

**Issue by holicc** [alexandreyc/adbc-rs#2]
I have no idea how to use this crate. Do you have any examples? Please.

**Comment by holicc** [comment]
How to get SQLite and PostgreSQL drivers libraries ?

**Comment by alexandreyc** [comment]
1. You should first build the SQLite and PostgreSQL drivers from the official ADBC repository
2. You can see an example of using the driver manager to load the SQLite driver in the `driver_manager` module documentation (`cargo doc --open --all-features`)

Please note that this implementation is being upstreamed in the official ABDC repository and so it will become obsolete very soon.

**Comment by holicc** [comment]
> 1. You should first build the SQLite and PostgreSQL drivers from the official ADBC repository
> 2. You can see an example of using the driver manager to load the SQLite driver in the `driver_manager` module documentation (`cargo doc --open --all-features`)
> 
> Please note that this implementation is being upstreamed in the official ABDC repository and so it will become obsolete very soon.

Do you mean follow this [guide](https://github.com/holicc/arrow-adbc/blob/main/CONTRIBUTING.md#cc) to build drivers?

**Comment by alexandreyc** [comment]
Yes!
